# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import gateway_pb2 as gateway__pb2


class AVRGatewayStub(object):
  """サービスのまとめ
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SignUp = channel.unary_unary(
        '/gateway.AVRGateway/SignUp',
        request_serializer=gateway__pb2.SignUpRequest.SerializeToString,
        response_deserializer=gateway__pb2.SignUpResponse.FromString,
        )
    self.SignIn = channel.unary_unary(
        '/gateway.AVRGateway/SignIn',
        request_serializer=gateway__pb2.SignInRequest.SerializeToString,
        response_deserializer=gateway__pb2.SignInResponse.FromString,
        )
    self.Transaction = channel.unary_unary(
        '/gateway.AVRGateway/Transaction',
        request_serializer=gateway__pb2.TransactionRequest.SerializeToString,
        response_deserializer=gateway__pb2.TransactionResponse.FromString,
        )
    self.Balance = channel.unary_unary(
        '/gateway.AVRGateway/Balance',
        request_serializer=gateway__pb2.BalanceRequest.SerializeToString,
        response_deserializer=gateway__pb2.BalanceResponse.FromString,
        )
    self.History = channel.unary_unary(
        '/gateway.AVRGateway/History',
        request_serializer=gateway__pb2.HistoryRequest.SerializeToString,
        response_deserializer=gateway__pb2.HistoryResponse.FromString,
        )


class AVRGatewayServicer(object):
  """サービスのまとめ
  """

  def SignUp(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SignIn(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Transaction(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Balance(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def History(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AVRGatewayServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SignUp': grpc.unary_unary_rpc_method_handler(
          servicer.SignUp,
          request_deserializer=gateway__pb2.SignUpRequest.FromString,
          response_serializer=gateway__pb2.SignUpResponse.SerializeToString,
      ),
      'SignIn': grpc.unary_unary_rpc_method_handler(
          servicer.SignIn,
          request_deserializer=gateway__pb2.SignInRequest.FromString,
          response_serializer=gateway__pb2.SignInResponse.SerializeToString,
      ),
      'Transaction': grpc.unary_unary_rpc_method_handler(
          servicer.Transaction,
          request_deserializer=gateway__pb2.TransactionRequest.FromString,
          response_serializer=gateway__pb2.TransactionResponse.SerializeToString,
      ),
      'Balance': grpc.unary_unary_rpc_method_handler(
          servicer.Balance,
          request_deserializer=gateway__pb2.BalanceRequest.FromString,
          response_serializer=gateway__pb2.BalanceResponse.SerializeToString,
      ),
      'History': grpc.unary_unary_rpc_method_handler(
          servicer.History,
          request_deserializer=gateway__pb2.HistoryRequest.FromString,
          response_serializer=gateway__pb2.HistoryResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'gateway.AVRGateway', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
